#!/bin/bash
run_latehook()
{
    # Now mount the host filesystem
    # mkdir /host
    # mount -t vfat /dev/sda1 /host

    # And the loop filesystem
    losetup -r /dev/loop0 /new_root/root.img
    mount -t ext4 -o ro,noload /dev/loop0 /new_root
    # mount --bind /host /new_root/host
}

